# ET0737 Lab 2: NumPy Fundamentals

## Introduction to Numerical Computing with NumPy

Welcome to Lab 2! In this notebook, you will learn the fundamentals of NumPy, the cornerstone library for numerical computing in Python.

### What is NumPy?

NumPy (Numerical Python) is a powerful library that provides:
- High-performance multidimensional array objects
- Tools for working with arrays
- Mathematical functions for array operations
- Linear algebra, Fourier transform, and random number capabilities

### Why Use NumPy?

1. **Performance**: NumPy operations are significantly faster than pure Python
2. **Memory Efficiency**: NumPy arrays use less memory than Python lists
3. **Convenient**: Provides vectorized operations and broadcasting
4. **Foundation**: Forms the basis for other scientific libraries (Pandas, Matplotlib, SciPy)

### Learning Objectives

By the end of this lab, you will be able to:
- Create and manipulate NumPy arrays
- Understand array properties and dimensions
- Perform array operations and broadcasting
- Reshape and flatten arrays
- Use indexing and slicing techniques
- Stack and concatenate arrays
- Perform matrix operations
- Apply statistical functions and universal functions

---
## Section 1: Getting Started with NumPy

First, let's import NumPy and check its version.

In [3]:
# Import NumPy library
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.4


---
## Section 2: Creating NumPy Arrays

NumPy arrays are the fundamental data structure in NumPy. Let's explore different ways to create them.

### 2.1 Creating Arrays from Python Lists

In [2]:
# Create a 1D array from a list
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print(f"Type: {type(arr1d)}")

1D Array:
[1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [3]:
# Create a 2D array from nested lists
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Create a 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:")
print(arr3d)
print(f"\nShape: {arr3d.shape}")

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape: (2, 2, 2)


### 2.2 Array Properties

Every NumPy array has important properties that define its structure.

In [5]:
# Array properties
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f"Shape (dimensions): {arr.shape}")  # (rows, columns)
print(f"Number of dimensions: {arr.ndim}")
print(f"Total number of elements: {arr.size}")
print(f"Data type: {arr.dtype}")
print(f"Item size (bytes): {arr.itemsize}")
print(f"Total bytes: {arr.nbytes}")

Shape (dimensions): (2, 4)
Number of dimensions: 2
Total number of elements: 8
Data type: int32
Item size (bytes): 4
Total bytes: 32


### 2.3 Array Creation Functions

NumPy provides several convenient functions to create arrays with specific values.

In [6]:
# Create array of zeros
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Array of zeros:")
print(zeros)

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# Create array of ones
ones = np.ones((2, 3, 4))  # 3D array
print("Array of ones (shape 2x3x4):")
print(ones)

Array of ones (shape 2x3x4):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
# Create array with a constant value
full = np.full((3, 3), 7)
print("Array filled with 7:")
print(full)

Array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [9]:
# Create identity matrix
identity = np.eye(4)
print("Identity matrix (4x4):")
print(identity)

Identity matrix (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# Create array with range of values
range_arr = np.arange(0, 20, 2)  # start, stop, step
print("Array with range (0 to 20, step 2):")
print(range_arr)

Array with range (0 to 20, step 2):
[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
# Create array with linearly spaced values
linspace_arr = np.linspace(0, 1, 5)  # start, stop, number of points
print("Array with 5 values from 0 to 1:")
print(linspace_arr)

Array with 5 values from 0 to 1:
[0.   0.25 0.5  0.75 1.  ]


In [12]:
# Create array with random values
np.random.seed(42)  # For reproducibility
random_arr = np.random.random((2, 3))  # Uniform distribution [0, 1)
print("Array with random values:")
print(random_arr)

random_int = np.random.randint(0, 100, size=(3, 3))  # Random integers
print("\nArray with random integers (0-100):")
print(random_int)

Array with random values:
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

Array with random integers (0-100):
[[74 74 87]
 [99 23  2]
 [21 52  1]]


### 📝 Section 2 Exercises

Practice creating NumPy arrays with these exercises.

In [5]:
# EXERCISE 1: Create a 1D array containing the numbers 10 to 50 with step 5
# Your code here:
exercise1 = np.arange(10,51,5)
print(exercise1)

[10 15 20 25 30 35 40 45 50]


In [14]:
# SOLUTION 1:
exercise1 = np.arange(10, 51, 5)
print("Exercise 1 - Array from 10 to 50, step 5:")
print(exercise1)

Exercise 1 - Array from 10 to 50, step 5:
[10 15 20 25 30 35 40 45 50]


In [6]:
# EXERCISE 2: Create a 3x3 array filled with the value 9.5
# Your code here:
exercise2 = np.full((3,3),9.5)
print(exercise2)

[[9.5 9.5 9.5]
 [9.5 9.5 9.5]
 [9.5 9.5 9.5]]


In [16]:
# SOLUTION 2:
exercise2 = np.full((3, 3), 9.5)
print("Exercise 2 - 3x3 array filled with 9.5:")
print(exercise2)

Exercise 2 - 3x3 array filled with 9.5:
[[9.5 9.5 9.5]
 [9.5 9.5 9.5]
 [9.5 9.5 9.5]]


In [12]:
# EXERCISE 3: Create a 2D array of shape (4, 5) with random integers between 1 and 50
# Your code here:
np.random.seed(42) # Towel
exercise3 = np.random.randint(1,51, size = (4,5))
print(exercise3)


[[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]]


In [18]:
# SOLUTION 3:
np.random.seed(123)
exercise3 = np.random.randint(1, 51, size=(4, 5))
print("Exercise 3 - 4x5 array with random integers (1-50):")
print(exercise3)

Exercise 3 - 4x5 array with random integers (1-50):
[[46  3 29 35 39]
 [18 20 43 23 34]
 [33 50 48 10 33]
 [47 33 48 26 20]]


In [7]:
# EXERCISE 4: Create an array with 10 evenly spaced values between 5 and 10
# Your code here:
exercise4 = np.linspace(5,10,10)
print(exercise4)

[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]


In [20]:
# SOLUTION 4:
exercise4 = np.linspace(5, 10, 10)
print("Exercise 4 - 10 evenly spaced values from 5 to 10:")
print(exercise4)

Exercise 4 - 10 evenly spaced values from 5 to 10:
[ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]


In [9]:
# EXERCISE 5: Create a 5x5 identity matrix and print its diagonal
# Your code here:
exercise5 = np.eye(5)
print(np.diag(exercise5))

[1. 1. 1. 1. 1.]


In [22]:
# SOLUTION 5:
exercise5 = np.eye(5)
print("Exercise 5 - 5x5 identity matrix:")
print(exercise5)
print("\nDiagonal elements:")
print(np.diag(exercise5))

Exercise 5 - 5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


---
## Section 3: Array Operations and Broadcasting

NumPy enables element-wise operations and broadcasting, making mathematical operations fast and intuitive.

### 3.1 Element-wise Operations

In [23]:
# Create sample arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Array 1:", arr1)
print("Array 2:", arr2)
print("\nElement-wise operations:")
print("Addition:", arr1 + arr2)
print("Subtraction:", arr2 - arr1)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)
print("Power:", arr1 ** 2)

Array 1: [1 2 3 4]
Array 2: [10 20 30 40]

Element-wise operations:
Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [ 1  4  9 16]


### 3.2 Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes.

In [24]:
# Broadcasting with scalar
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print("Add 10:", arr + 10)
print("Multiply by 3:", arr * 3)
print("Divide by 2:", arr / 2)

Original array: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]


In [25]:
# Broadcasting with 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
row_vec = np.array([10, 20, 30])

print("2D Array:")
print(arr_2d)
print("\nRow vector:", row_vec)
print("\nBroadcasted addition:")
print(arr_2d + row_vec)

2D Array:
[[1 2 3]
 [4 5 6]]

Row vector: [10 20 30]

Broadcasted addition:
[[11 22 33]
 [14 25 36]]


### 3.3 Universal Functions (ufuncs)

NumPy provides fast element-wise mathematical functions.

In [26]:
# Universal functions
arr = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Array (radians):", arr)
print("\nTrigonometric functions:")
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))
print("tan:", np.tan(arr))

Array (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Trigonometric functions:
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [27]:
# Exponential and logarithmic functions
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("\nExponential and log:")
print("exp:", np.exp(arr))
print("log (natural):", np.log(arr))
print("log10:", np.log10(arr))
print("sqrt:", np.sqrt(arr))

Array: [1 2 3 4 5]

Exponential and log:
exp: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log (natural): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log10: [0.         0.30103    0.47712125 0.60205999 0.69897   ]
sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


---
## Section 4: Reshaping and Flattening Arrays

NumPy provides flexible ways to change the shape of arrays without changing their data.

### 4.1 Reshaping Arrays

In [28]:
# Create a 1D array and reshape it
arr = np.arange(12)
print("Original 1D array:", arr)

# Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("\nReshaped to 3x4:")
print(arr_2d)

# Reshape to 3D
arr_3d = arr.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:")
print(arr_3d)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x2x3:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [29]:
# Using -1 for automatic dimension calculation
arr = np.arange(24)
print("Original array (24 elements):", arr)

# NumPy calculates the missing dimension
arr_auto = arr.reshape(4, -1)  # -1 automatically becomes 6
print("\nReshape to (4, -1) -> becomes (4, 6):")
print(arr_auto)

arr_auto2 = arr.reshape(-1, 3)  # -1 automatically becomes 8
print("\nReshape to (-1, 3) -> becomes (8, 3):")
print(arr_auto2)

Original array (24 elements): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshape to (4, -1) -> becomes (4, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshape to (-1, 3) -> becomes (8, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


### 4.2 Flattening Arrays

In [30]:
# Flatten a multi-dimensional array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(arr_2d)

# Using flatten() - creates a copy
flattened = arr_2d.flatten()
print("\nFlattened (using flatten()):")
print(flattened)

# Using ravel() - returns a view when possible
raveled = arr_2d.ravel()
print("\nFlattened (using ravel()):")
print(raveled)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened (using flatten()):
[1 2 3 4 5 6 7 8 9]

Flattened (using ravel()):
[1 2 3 4 5 6 7 8 9]


### 4.3 Transpose

In [31]:
# Transpose arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original (2x3):")
print(arr)

transposed = arr.T
print("\nTransposed (3x2):")
print(transposed)

# Alternative method
transposed2 = np.transpose(arr)
print("\nTransposed using np.transpose():")
print(transposed2)

Original (2x3):
[[1 2 3]
 [4 5 6]]

Transposed (3x2):
[[1 4]
 [2 5]
 [3 6]]

Transposed using np.transpose():
[[1 4]
 [2 5]
 [3 6]]


---
## Section 5: Array Indexing and Slicing

Indexing and slicing are powerful techniques to access and modify array elements.

### 5.1 Basic Indexing (1D Arrays)

In [32]:
# Basic indexing in 1D arrays
arr = np.array([10, 20, 30, 40, 50, 60])
print("Array:", arr)
print("\nIndexing:")
print("First element (index 0):", arr[0])
print("Third element (index 2):", arr[2])
print("Last element (index -1):", arr[-1])
print("Second to last (index -2):", arr[-2])

Array: [10 20 30 40 50 60]

Indexing:
First element (index 0): 10
Third element (index 2): 30
Last element (index -1): 60
Second to last (index -2): 50


In [33]:
# Basic slicing in 1D arrays
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:", arr)
print("\nSlicing:")
print("First 3 elements [0:3]:", arr[0:3])
print("Elements from index 2 to 5 [2:6]:", arr[2:6])
print("Every second element [::2]:", arr[::2])
print("Reverse array [::-1]:", arr[::-1])
print("Last 3 elements [-3:]:", arr[-3:])

Array: [10 20 30 40 50 60 70 80]

Slicing:
First 3 elements [0:3]: [10 20 30]
Elements from index 2 to 5 [2:6]: [30 40 50 60]
Every second element [::2]: [10 30 50 70]
Reverse array [::-1]: [80 70 60 50 40 30 20 10]
Last 3 elements [-3:]: [60 70 80]


### 5.2 2D Array Indexing

In [34]:
# 2D array indexing
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
print("2D Array:")
print(arr2d)
print("\n2D Indexing:")
print("Element at row 0, col 2:", arr2d[0, 2])
print("Element at row 2, col 3:", arr2d[2, 3])
print("\nRow access:")
print("First row:", arr2d[0])
print("Last row:", arr2d[-1])
print("\nColumn access:")
print("First column:", arr2d[:, 0])
print("Third column:", arr2d[:, 2])

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2D Indexing:
Element at row 0, col 2: 3
Element at row 2, col 3: 12

Row access:
First row: [1 2 3 4]
Last row: [ 9 10 11 12]

Column access:
First column: [1 5 9]
Third column: [ 3  7 11]


In [35]:
# 2D array slicing
print("2D Array:")
print(arr2d)
print("\n2D Slicing:")
print("First 2 rows, first 3 columns:")
print(arr2d[:2, :3])
print("\nAll rows, columns 1 and 2:")
print(arr2d[:, 1:3])
print("\nRows 1 and 2, all columns:")
print(arr2d[1:3, :])

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2D Slicing:
First 2 rows, first 3 columns:
[[1 2 3]
 [5 6 7]]

All rows, columns 1 and 2:
[[ 2  3]
 [ 6  7]
 [10 11]]

Rows 1 and 2, all columns:
[[ 5  6  7  8]
 [ 9 10 11 12]]


### 5.3 Boolean Indexing

In [36]:
# Boolean indexing
arr = np.array([1, 5, 10, 15, 20, 25, 30])
print("Array:", arr)

# Create boolean mask
mask = arr > 15
print("\nBoolean mask (arr > 15):", mask)
print("Elements > 15:", arr[mask])

# Directly use condition
print("\nElements >= 10 and <= 25:", arr[(arr >= 10) & (arr <= 25)])
print("Elements < 10 or > 20:", arr[(arr < 10) | (arr > 20)])

Array: [ 1  5 10 15 20 25 30]

Boolean mask (arr > 15): [False False False False  True  True  True]
Elements > 15: [20 25 30]

Elements >= 10 and <= 25: [10 15 20 25]
Elements < 10 or > 20: [ 1  5 25 30]


### 5.4 Fancy Indexing

In [37]:
# Fancy indexing with integer arrays
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Array:", arr)

# Use list of indices
indices = [0, 2, 5, 7]
print(f"\nElements at indices {indices}:", arr[indices])

# Use array of indices
ind_arr = np.array([1, 1, 3, 3, 5])
print(f"Elements at indices {ind_arr}:", arr[ind_arr])

Array: [10 20 30 40 50 60 70 80]

Elements at indices [0, 2, 5, 7]: [10 30 60 80]
Elements at indices [1 1 3 3 5]: [20 20 40 40 60]


In [38]:
# Fancy indexing in 2D
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print("2D Array:")
print(arr2d)

# Select specific rows
rows = [0, 2, 3]
print(f"\nRows {rows}:")
print(arr2d[rows])

# Select specific elements
row_idx = [0, 1, 2, 3]
col_idx = [2, 1, 0, 2]
print("\nSpecific elements (0,2), (1,1), (2,0), (3,2):")
print(arr2d[row_idx, col_idx])

2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Rows [0, 2, 3]:
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]

Specific elements (0,2), (1,1), (2,0), (3,2):
[ 3  5  7 12]


### 📝 Section 5 Exercises

In [39]:
# EXERCISE 6: Given the array below, extract all even numbers using boolean indexing
# arr = np.array([3, 8, 12, 15, 18, 21, 24, 27, 30])
# Your code here:


In [40]:
# SOLUTION 6:
arr = np.array([3, 8, 12, 15, 18, 21, 24, 27, 30])
even_numbers = arr[arr % 2 == 0]
print("Exercise 6 - Even numbers:")
print(even_numbers)

Exercise 6 - Even numbers:
[ 8 12 18 24 30]


In [41]:
# EXERCISE 7: Create a 5x5 array and extract the middle 3x3 subarray
# Your code here:


In [42]:
# SOLUTION 7:
arr = np.arange(1, 26).reshape(5, 5)
print("Exercise 7 - Original 5x5 array:")
print(arr)
middle = arr[1:4, 1:4]
print("\nMiddle 3x3 subarray:")
print(middle)

Exercise 7 - Original 5x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Middle 3x3 subarray:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [43]:
# EXERCISE 8: Use fancy indexing to select rows 0, 2, and 4 from the array
# arr = np.arange(50).reshape(10, 5)
# Your code here:


In [44]:
# SOLUTION 8:
arr = np.arange(50).reshape(10, 5)
print("Exercise 8 - Original 10x5 array:")
print(arr)
selected_rows = arr[[0, 2, 4]]
print("\nRows 0, 2, and 4:")
print(selected_rows)

Exercise 8 - Original 10x5 array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

Rows 0, 2, and 4:
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]


---
## Section 6: Array Stacking and Concatenation

NumPy provides functions to combine multiple arrays into larger arrays.

### 6.1 Vertical Stacking (vstack)

In [45]:
# Vertical stacking - stack arrays vertically (row-wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

vstacked = np.vstack((arr1, arr2))
print("\nVertically stacked:")
print(vstacked)
print(f"Shape: {vstacked.shape}")

Array 1: [1 2 3]
Array 2: [4 5 6]

Vertically stacked:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [46]:
# Vstack with 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

print("Array 1 (2x3):")
print(arr1)
print("\nArray 2 (1x3):")
print(arr2)

vstacked = np.vstack((arr1, arr2))
print("\nVertically stacked (3x3):")
print(vstacked)

Array 1 (2x3):
[[1 2 3]
 [4 5 6]]

Array 2 (1x3):
[[7 8 9]]

Vertically stacked (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 6.2 Horizontal Stacking (hstack)

In [47]:
# Horizontal stacking - stack arrays horizontally (column-wise)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

hstacked = np.hstack((arr1, arr2))
print("\nHorizontally stacked:")
print(hstacked)
print(f"Shape: {hstacked.shape}")

Array 1: [1 2 3]
Array 2: [4 5 6]

Horizontally stacked:
[1 2 3 4 5 6]
Shape: (6,)


In [48]:
# Hstack with 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1 (2x2):")
print(arr1)
print("\nArray 2 (2x2):")
print(arr2)

hstacked = np.hstack((arr1, arr2))
print("\nHorizontally stacked (2x4):")
print(hstacked)

Array 1 (2x2):
[[1 2]
 [3 4]]

Array 2 (2x2):
[[5 6]
 [7 8]]

Horizontally stacked (2x4):
[[1 2 5 6]
 [3 4 7 8]]


### 6.3 Concatenation

In [49]:
# Concatenate along specific axis
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

# Concatenate along axis 0 (rows)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenated along axis 0 (rows):")
print(concat_axis0)

# Concatenate along axis 1 (columns)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along axis 1 (columns):")
print(concat_axis1)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [50]:
# Concatenate multiple arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

result = np.concatenate((arr1, arr2, arr3))
print("Concatenate three 1D arrays:")
print(result)

Concatenate three 1D arrays:
[1 2 3 4 5 6 7 8 9]


### 6.4 Column and Row Stack

In [51]:
# Column stack - stack 1D arrays as columns
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Array 1:", arr1)
print("Array 2:", arr2)

column_stacked = np.column_stack((arr1, arr2))
print("\nColumn stacked:")
print(column_stacked)

Array 1: [1 2 3]
Array 2: [4 5 6]

Column stacked:
[[1 4]
 [2 5]
 [3 6]]


In [52]:
# Row stack - equivalent to vstack
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

row_stacked = np.row_stack((arr1, arr2))
print("Row stacked:")
print(row_stacked)

Row stacked:
[[1 2 3]
 [4 5 6]]


### 📝 Section 6 Exercises

In [53]:
# EXERCISE 9: Stack these three arrays vertically
# arr1 = np.array([1, 2, 3])
# arr2 = np.array([4, 5, 6])
# arr3 = np.array([7, 8, 9])
# Your code here:


In [54]:
# SOLUTION 9:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
result = np.vstack((arr1, arr2, arr3))
print("Exercise 9 - Vertically stacked:")
print(result)

Exercise 9 - Vertically stacked:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# EXERCISE 10: Create a 4x4 array by concatenating four 2x2 arrays
# Arrange them in a 2x2 grid pattern
# Your code here:


In [56]:
# SOLUTION 10:
top_left = np.array([[1, 2], [3, 4]])
top_right = np.array([[5, 6], [7, 8]])
bottom_left = np.array([[9, 10], [11, 12]])
bottom_right = np.array([[13, 14], [15, 16]])

top = np.hstack((top_left, top_right))
bottom = np.hstack((bottom_left, bottom_right))
result = np.vstack((top, bottom))

print("Exercise 10 - 4x4 array from four 2x2 arrays:")
print(result)

Exercise 10 - 4x4 array from four 2x2 arrays:
[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]


In [57]:
# EXERCISE 11: Create two 1D arrays and use column_stack to create a 2-column matrix
# arr1 should be [10, 20, 30, 40]
# arr2 should be [100, 200, 300, 400]
# Your code here:


In [58]:
# SOLUTION 11:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([100, 200, 300, 400])
result = np.column_stack((arr1, arr2))
print("Exercise 11 - Column stacked:")
print(result)

Exercise 11 - Column stacked:
[[ 10 100]
 [ 20 200]
 [ 30 300]
 [ 40 400]]


---
## Section 7: Matrix Operations and Multiplication

Matrices are 2D arrays and NumPy provides comprehensive support for matrix operations.

### 7.1 Creating Matrices

In [59]:
# Create matrices
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])
                     
matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

print("Matrix A (2x3):")
print(matrix_a)
print("\nMatrix B (3x2):")
print(matrix_b)

Matrix A (2x3):
[[1 2 3]
 [4 5 6]]

Matrix B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]


### 7.2 Matrix Multiplication

In [60]:
# Matrix multiplication using @ operator (Python 3.5+)
result = matrix_a @ matrix_b
print("Matrix A @ Matrix B:")
print(result)
print(f"Shape: {result.shape}")

Matrix A @ Matrix B:
[[ 58  64]
 [139 154]]
Shape: (2, 2)


In [61]:
# Matrix multiplication using np.dot()
result_dot = np.dot(matrix_a, matrix_b)
print("Using np.dot():")
print(result_dot)

Using np.dot():
[[ 58  64]
 [139 154]]


In [62]:
# Matrix multiplication using np.matmul()
result_matmul = np.matmul(matrix_a, matrix_b)
print("Using np.matmul():")
print(result_matmul)

Using np.matmul():
[[ 58  64]
 [139 154]]


### 7.3 Element-wise vs Matrix Multiplication

In [63]:
# Element-wise multiplication (different from matrix multiplication)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix A:")
print(a)
print("\nMatrix B:")
print(b)

# Element-wise multiplication
elem_mult = a * b
print("\nElement-wise multiplication (a * b):")
print(elem_mult)

# Matrix multiplication
matrix_mult = a @ b
print("\nMatrix multiplication (a @ b):")
print(matrix_mult)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise multiplication (a * b):
[[ 5 12]
 [21 32]]

Matrix multiplication (a @ b):
[[19 22]
 [43 50]]


### 7.4 Matrix Properties and Operations

In [64]:
# Matrix properties
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:")
print(matrix)

# Transpose
print("\nTranspose:")
print(matrix.T)

# Diagonal
print("\nDiagonal elements:")
print(np.diag(matrix))

# Trace (sum of diagonal elements)
print(f"\nTrace: {np.trace(matrix)}")

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Diagonal elements:
[1 5 9]

Trace: 15


In [65]:
# Matrix determinant and inverse (for square matrices)
matrix = np.array([[1, 2],
                   [3, 4]])

print("Matrix:")
print(matrix)

# Determinant
det = np.linalg.det(matrix)
print(f"\nDeterminant: {det}")

# Inverse
inv = np.linalg.inv(matrix)
print("\nInverse:")
print(inv)

# Verify: A @ A_inv = Identity
identity = matrix @ inv
print("\nMatrix @ Inverse (should be identity):")
print(np.round(identity, 10))  # Round to handle floating point errors

Matrix:
[[1 2]
 [3 4]]

Determinant: -2.0000000000000004

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]

Matrix @ Inverse (should be identity):
[[1. 0.]
 [0. 1.]]


In [66]:
# Identity matrix
identity_3 = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_3)

# Matrix power
matrix = np.array([[1, 2],
                   [0, 1]])
print("\nOriginal Matrix:")
print(matrix)

matrix_squared = np.linalg.matrix_power(matrix, 2)
print("\nMatrix squared:")
print(matrix_squared)

matrix_cubed = np.linalg.matrix_power(matrix, 3)
print("\nMatrix cubed:")
print(matrix_cubed)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Original Matrix:
[[1 2]
 [0 1]]

Matrix squared:
[[1 4]
 [0 1]]

Matrix cubed:
[[1 6]
 [0 1]]


### 7.5 Solving Linear Systems

In [67]:
# Solve linear system Ax = b
# Example: 2x + 3y = 8
#          4x + y = 9

A = np.array([[2, 3],
              [4, 1]])
b = np.array([8, 9])

print("Solving: Ax = b")
print("\nMatrix A:")
print(A)
print("\nVector b:")
print(b)

# Solve for x
x = np.linalg.solve(A, b)
print("\nSolution x:")
print(x)
print(f"\nx = {x[0]}, y = {x[1]}")

# Verify solution
verify = A @ x
print("\nVerification (A @ x):")
print(verify)
print("Expected b:", b)

Solving: Ax = b

Matrix A:
[[2 3]
 [4 1]]

Vector b:
[8 9]

Solution x:
[1.9 1.4]

x = 1.9, y = 1.4

Verification (A @ x):
[8. 9.]
Expected b: [8 9]


### 📝 Section 7 Exercises

In [68]:
# EXERCISE 12: Create two matrices and perform matrix multiplication
# Matrix A: [[2, 1], [1, 3]]
# Matrix B: [[4, 2], [1, 5]]
# Your code here:


In [69]:
# SOLUTION 12:
A = np.array([[2, 1], [1, 3]])
B = np.array([[4, 2], [1, 5]])
result = A @ B
print("Exercise 12 - Matrix multiplication:")
print("A @ B =")
print(result)

Exercise 12 - Matrix multiplication:
A @ B =
[[ 9  9]
 [ 7 17]]


In [70]:
# EXERCISE 13: Calculate the determinant and inverse of the matrix [[3, 1], [2, 4]]
# Your code here:


In [71]:
# SOLUTION 13:
matrix = np.array([[3, 1], [2, 4]])
det = np.linalg.det(matrix)
inv = np.linalg.inv(matrix)
print("Exercise 13 - Determinant and Inverse:")
print(f"Determinant: {det}")
print("Inverse:")
print(inv)

Exercise 13 - Determinant and Inverse:
Determinant: 10.000000000000002
Inverse:
[[ 0.4 -0.1]
 [-0.2  0.3]]


In [72]:
# EXERCISE 14: Solve the linear system:
# 3x + 2y = 7
# 5x + y = 11
# Your code here:


In [73]:
# SOLUTION 14:
A = np.array([[3, 2], [5, 1]])
b = np.array([7, 11])
x = np.linalg.solve(A, b)
print("Exercise 14 - Solve linear system:")
print(f"x = {x[0]}, y = {x[1]}")
print("\nVerification:")
print(f"3*{x[0]} + 2*{x[1]} = {3*x[0] + 2*x[1]}")
print(f"5*{x[0]} + 1*{x[1]} = {5*x[0] + 1*x[1]}")

Exercise 14 - Solve linear system:
x = 2.142857142857143, y = 0.2857142857142859

Verification:
3*2.142857142857143 + 2*0.2857142857142859 = 7.000000000000001
5*2.142857142857143 + 1*0.2857142857142859 = 11.0


---
## Section 8: Statistical Operations

NumPy provides comprehensive statistical functions for data analysis.

### 8.1 Basic Statistics

In [74]:
# Create sample data
data = np.array([12, 15, 18, 21, 24, 27, 30, 33, 36])

print("Data:", data)
print("\nBasic Statistics:")
print(f"Sum: {np.sum(data)}")
print(f"Mean (average): {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard deviation: {np.std(data)}")
print(f"Variance: {np.var(data)}")
print(f"Minimum: {np.min(data)}")
print(f"Maximum: {np.max(data)}")

Data: [12 15 18 21 24 27 30 33 36]

Basic Statistics:
Sum: 216
Mean (average): 24.0
Median: 24.0
Standard deviation: 7.745966692414834
Variance: 60.0
Minimum: 12
Maximum: 36


In [75]:
# Statistics on 2D arrays
data_2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

print("2D Array:")
print(data_2d)

print("\nStatistics on entire array:")
print(f"Sum: {np.sum(data_2d)}")
print(f"Mean: {np.mean(data_2d)}")

print("\nStatistics along axis 0 (columns):")
print(f"Sum: {np.sum(data_2d, axis=0)}")
print(f"Mean: {np.mean(data_2d, axis=0)}")

print("\nStatistics along axis 1 (rows):")
print(f"Sum: {np.sum(data_2d, axis=1)}")
print(f"Mean: {np.mean(data_2d, axis=1)}")

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Statistics on entire array:
Sum: 78
Mean: 6.5

Statistics along axis 0 (columns):
Sum: [15 18 21 24]
Mean: [5. 6. 7. 8.]

Statistics along axis 1 (rows):
Sum: [10 26 42]
Mean: [ 2.5  6.5 10.5]


### 8.2 Finding Positions

In [76]:
# Finding min/max positions
data = np.array([23, 15, 42, 8, 16, 35, 19])

print("Data:", data)
print(f"\nMinimum value: {np.min(data)}")
print(f"Index of minimum: {np.argmin(data)}")
print(f"Maximum value: {np.max(data)}")
print(f"Index of maximum: {np.argmax(data)}")

Data: [23 15 42  8 16 35 19]

Minimum value: 8
Index of minimum: 3
Maximum value: 42
Index of maximum: 2


In [77]:
# Finding positions in 2D arrays
data_2d = np.array([[12, 45, 23],
                    [67, 31, 89],
                    [15, 78, 34]])

print("2D Array:")
print(data_2d)
print(f"\nMaximum value: {np.max(data_2d)}")
print(f"Flat index of maximum: {np.argmax(data_2d)}")

# Convert flat index to 2D coordinates
max_idx = np.argmax(data_2d)
max_row, max_col = np.unravel_index(max_idx, data_2d.shape)
print(f"Position of maximum: row {max_row}, column {max_col}")

2D Array:
[[12 45 23]
 [67 31 89]
 [15 78 34]]

Maximum value: 89
Flat index of maximum: 5
Position of maximum: row 1, column 2


### 8.3 Percentiles and Quantiles

In [78]:
# Percentiles
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Data:", data)
print(f"\n25th percentile (Q1): {np.percentile(data, 25)}")
print(f"50th percentile (Median/Q2): {np.percentile(data, 50)}")
print(f"75th percentile (Q3): {np.percentile(data, 75)}")
print(f"\n90th percentile: {np.percentile(data, 90)}")

Data: [ 10  20  30  40  50  60  70  80  90 100]

25th percentile (Q1): 32.5
50th percentile (Median/Q2): 55.0
75th percentile (Q3): 77.5

90th percentile: 91.0


### 8.4 Correlation and Covariance

In [79]:
# Correlation coefficient
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])  # Perfect correlation

print("x:", x)
print("y:", y)

# Correlation matrix
corr_matrix = np.corrcoef(x, y)
print("\nCorrelation matrix:")
print(corr_matrix)
print(f"\nCorrelation coefficient: {corr_matrix[0, 1]}")

x: [1 2 3 4 5]
y: [ 2  4  6  8 10]

Correlation matrix:
[[1. 1.]
 [1. 1.]]

Correlation coefficient: 0.9999999999999999


In [80]:
# Covariance
print("x:", x)
print("y:", y)

cov_matrix = np.cov(x, y)
print("\nCovariance matrix:")
print(cov_matrix)
print(f"\nCovariance: {cov_matrix[0, 1]}")

x: [1 2 3 4 5]
y: [ 2  4  6  8 10]

Covariance matrix:
[[ 2.5  5. ]
 [ 5.  10. ]]

Covariance: 5.0


### 8.5 Cumulative Operations

In [81]:
# Cumulative sum and product
arr = np.array([1, 2, 3, 4, 5])

print("Array:", arr)
print("\nCumulative sum:", np.cumsum(arr))
print("Cumulative product:", np.cumprod(arr))

Array: [1 2 3 4 5]

Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


In [82]:
# Cumulative operations on 2D arrays
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("2D Array:")
print(arr_2d)

print("\nCumulative sum (flattened):")
print(np.cumsum(arr_2d))

print("\nCumulative sum along axis 0 (down columns):")
print(np.cumsum(arr_2d, axis=0))

print("\nCumulative sum along axis 1 (across rows):")
print(np.cumsum(arr_2d, axis=1))

2D Array:
[[1 2 3]
 [4 5 6]]

Cumulative sum (flattened):
[ 1  3  6 10 15 21]

Cumulative sum along axis 0 (down columns):
[[1 2 3]
 [5 7 9]]

Cumulative sum along axis 1 (across rows):
[[ 1  3  6]
 [ 4  9 15]]


### 8.6 Sorting

In [83]:
# Sorting arrays
arr = np.array([64, 25, 12, 22, 11, 90, 88])

print("Original array:", arr)
print("Sorted array:", np.sort(arr))
print("Indices that would sort the array:", np.argsort(arr))

Original array: [64 25 12 22 11 90 88]
Sorted array: [11 12 22 25 64 88 90]
Indices that would sort the array: [4 2 3 1 0 6 5]


In [84]:
# Sorting 2D arrays
arr_2d = np.array([[3, 1, 4],
                   [9, 2, 6],
                   [5, 8, 7]])

print("Original 2D array:")
print(arr_2d)

print("\nSort along axis 0 (each column):")
print(np.sort(arr_2d, axis=0))

print("\nSort along axis 1 (each row):")
print(np.sort(arr_2d, axis=1))

Original 2D array:
[[3 1 4]
 [9 2 6]
 [5 8 7]]

Sort along axis 0 (each column):
[[3 1 4]
 [5 2 6]
 [9 8 7]]

Sort along axis 1 (each row):
[[1 3 4]
 [2 6 9]
 [5 7 8]]


### 📝 Section 8 Exercises

In [85]:
# EXERCISE 15: Given the array [45, 67, 23, 89, 12, 56, 78], calculate:
# - Mean, median, standard deviation
# - Find the index of the maximum value
# Your code here:


In [86]:
# SOLUTION 15:
data = np.array([45, 67, 23, 89, 12, 56, 78])
print("Exercise 15 - Statistical Analysis:")
print(f"Data: {data}")
print(f"Mean: {np.mean(data):.2f}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data):.2f}")
print(f"Maximum value: {np.max(data)}")
print(f"Index of maximum: {np.argmax(data)}")

Exercise 15 - Statistical Analysis:
Data: [45 67 23 89 12 56 78]
Mean: 52.86
Median: 56.0
Standard Deviation: 26.11
Maximum value: 89
Index of maximum: 3


In [87]:
# EXERCISE 16: Create a 4x4 array of random integers between 1 and 50
# Calculate the sum of each row and each column
# Your code here:


In [88]:
# SOLUTION 16:
np.random.seed(42)
data = np.random.randint(1, 51, size=(4, 4))
print("Exercise 16 - Row and Column Sums:")
print("Array:")
print(data)
print("\nSum of each row:", np.sum(data, axis=1))
print("Sum of each column:", np.sum(data, axis=0))

Exercise 16 - Row and Column Sums:
Array:
[[39 29 15 43]
 [ 8 21 39 19]
 [23 11 11 24]
 [36 40 24  3]]

Sum of each row: [126  87  69 103]
Sum of each column: [106 101  89  89]


In [89]:
# EXERCISE 17: Sort the array [34, 12, 78, 23, 56, 45] and find the 25th, 50th, and 75th percentiles
# Your code here:


In [90]:
# SOLUTION 17:
data = np.array([34, 12, 78, 23, 56, 45])
print("Exercise 17 - Sorting and Percentiles:")
print(f"Original: {data}")
print(f"Sorted: {np.sort(data)}")
print(f"\n25th percentile (Q1): {np.percentile(data, 25)}")
print(f"50th percentile (Median): {np.percentile(data, 50)}")
print(f"75th percentile (Q3): {np.percentile(data, 75)}")

Exercise 17 - Sorting and Percentiles:
Original: [34 12 78 23 56 45]
Sorted: [12 23 34 45 56 78]

25th percentile (Q1): 25.75
50th percentile (Median): 39.5
75th percentile (Q3): 53.25


---
## Summary and Conclusion

### What You've Learned

Congratulations! You've completed the NumPy Fundamentals lab. Here's what you've mastered:

#### **1. Array Creation**
- Creating arrays from lists (1D, 2D, 3D)
- Array properties: shape, ndim, size, dtype
- Array creation functions: zeros, ones, full, eye, arange, linspace, random

#### **2. Array Operations**
- Element-wise arithmetic operations
- Broadcasting for operations on different-shaped arrays
- Universal functions (ufuncs) for mathematical operations

#### **3. Reshaping and Transformation**
- Reshaping arrays with reshape()
- Flattening multi-dimensional arrays
- Transposing arrays

#### **4. Indexing and Slicing**
- Basic indexing and slicing for 1D and 2D arrays
- Boolean indexing for conditional selection
- Fancy indexing with index arrays

#### **5. Array Stacking**
- Vertical stacking (vstack)
- Horizontal stacking (hstack)
- Concatenation along specific axes
- Column and row stacking

#### **6. Matrix Operations**
- Matrix multiplication (@ operator, dot, matmul)
- Matrix properties (transpose, diagonal, trace)
- Matrix determinant and inverse
- Solving linear systems

#### **7. Statistical Operations**
- Basic statistics: mean, median, std, variance, min, max
- Finding positions with argmin and argmax
- Percentiles and quantiles
- Correlation and covariance
- Cumulative operations and sorting

### Next Steps

Now that you've mastered NumPy fundamentals, you're ready to:
1. **Lab 3**: Learn Matplotlib for data visualization and Pandas for data manipulation
2. **Lab 4**: Apply your skills to real-world data analysis and preprocessing
3. **Practice**: Work with larger datasets and complex numerical computations
4. **Explore**: Dive deeper into scientific computing with SciPy

### Key Takeaways

✅ **NumPy is fast**: Vectorized operations are much faster than Python loops  
✅ **Arrays are powerful**: Multi-dimensional arrays enable complex data operations  
✅ **Broadcasting is convenient**: Perform operations on different-shaped arrays automatically  
✅ **Rich functionality**: NumPy provides comprehensive mathematical and statistical functions  

### Resources for Further Learning

- **Official Documentation**: https://numpy.org/doc/
- **NumPy Tutorial**: https://numpy.org/doc/stable/user/quickstart.html
- **Practice Problems**: https://www.w3resource.com/python-exercises/numpy/index.php

### Keep Practicing!

The best way to master NumPy is through practice. Try working with real datasets, experimenting with different array operations, and solving numerical problems.

**Happy Computing! 🎉**